@host=http://localhost:5000


GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZGJiYTU4OS1kMTczLTQwNGEtYTk1NC05MTFkMGUyODUwZWYiLCJnaXZlbl9uYW1lIjoiUnV3YW4iLCJmYW1pbHlfbmFtZSI6IldlZXJhc2VuYSIsImp0aSI6ImUwOTdjZGQyLWNlNWItNDE3ZS1iNDk0LTgxYmM3OWQzYmQ3MCIsImV4cCI6MTY4NDY3NTA4MCwiaXNzIjoiQnViYmVyIERpbm5lciIsImF1ZCI6IkJ1YmJlciBEaW5uZXIifQ.QWY9fjFng3wRXsPPdLHMSDhJ2m3eCuQciIfX8mXV8k8

