@host=http://localhost:5000
# http://localhost:8081

POST {{host}}/auth/Register
Content-Type: application/json

{
    "firstName": "Ruwan",
    "lastName" : "Weerasena",
    "email":"Ruwan@gmail.com",
    "password":"Ruwan"
}

