@host=http://localhost:5000
# http://localhost:8081


POST {{host}}/auth/Register
Content-Type: application/json

{
    "firstName": "Amichi",
    "lastName" : "MantinBand",
    "email":"amicha@gmail.com",
    "password":"amico"
}

